
name: Run Swift Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Swift Testing Dependencies
        run: swift package resolve

      - name: Run Tests
        run: swift test
